services:
  # Backend API Service
  - type: web
    name: sirim-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    
  # Frontend Static Site
  - type: static
    name: sirim-app
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: sirim-backend
          property: host
